name: Backport merged pull request
on:
  pull_request_target:
    types: [closed]
  issue_comment:
    types: [created]
permissions:
  contents: write # so it can comment
  pull-requests: write # so it can create pull requests
jobs:
  backport:
    name: Backport pull request
    runs-on: ubuntu-latest
    # Don't run on closed unmerged pull requests
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v4
      - name: Create backport pull requests
        uses: korthout/backport-action@v2
        with:
          # Token to authenticate requests to GitHub
          github_token: ${{ secrets.BACKPORT_ACTION_PAT }}
          label_pattern: "^Backport ([^ ]+)$"
          merge_commits: skip
  backport-labels:
    name: Backport failed labels
    runs-on: ubuntu-latest
    if: >
      # TODO: Change user id
      (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.id != 200230 &&
        startsWith(github.event.comment.body, 'Backport failed')
      )
    steps:
      - name: Add Backport failed label to PR
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.BACKPORT_ACTION_PAT }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.issue.number;
            const labelToAdd = "Backport failed";

            // Add the label to the PR
            await github.issues.addLabels({
              owner,
              repo,
              issue_number: prNumber,
              labels: [labelToAdd]
            });
